### ISSUE TITLE
Cannot build examples

### ISSUE THREAD

**Issue by oguzhancebe** [vsamy/wrench-cone-lib#2]
Hello,

I followed the instructions and installed the package using PID, but when I execute `make build` to build examples, I get the following error:
Running CMake to regenerate build system...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/oguz/pid-workspace/packages/wrench-cone-lib/build/debug
-- Configuring done
-- Generating done
-- Build files have been written to: /home/oguz/pid-workspace/packages/wrench-cone-lib/build/release
-- Configuring done
-- Generating done
-- Build files have been written to: /home/oguz/pid-workspace/packages/wrench-cone-lib/build
[ 60%] Built target reconfigure
[ 80%] [PID] Checking branch...
CMake Error at /home/oguz/pid-workspace/share/cmake/system/Check_PID_Package_Branch.cmake:27 (message):
  [PID] ERROR : wrench-cone-lib must be built on a development branch
  (integration or feature specific branch).

CMakeFiles/check-branch.dir/build.make:57: recipe for target 'CMakeFiles/check-branch' failed
make[3]: *** [CMakeFiles/check-branch] Error 1
CMakeFiles/Makefile2:259: recipe for target 'CMakeFiles/check-branch.dir/all' failed
make[2]: *** [CMakeFiles/check-branch.dir/all] Error 2
CMakeFiles/Makefile2:396: recipe for target 'CMakeFiles/build.dir/rule' failed
make[1]: *** [CMakeFiles/build.dir/rule] Error 2
Makefile:248: recipe for target 'build' failed
make: *** [build] Error 2

I get the same error even I turn examples OFF in ccmake.. and try building it.

Regards

**Comment by vsamy** [comment]
You have to switch to the development branch.

```bash
git checkout integration
```

The master branch cannot be modified without the approbation of the main developer. This is done to avoid conflicts.
